//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;

	public partial class Ticket : IEntity
	{
		public int DocId { get; set; }
		public System.DateTime Time { get; set; }
		public System.Guid CardNumber { get; set; }
		public System.DateTime CreationTime { get; set; }
		public bool ConfirmationStatus { get; set; }
		public string Complaint { get; set; }

		public virtual Patient Patient { get; set; }
		public virtual Doctor Doctor { get; set; }
		public EntityState EntityState { get; set; }
	}
}
